// _examples/rating/rating-min-max.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <FormKit type="form" actions={false}>
      {({ value }) => (
        <>
          {/* %partial% */}
          <FormKit
            type="rating"
            min={1}
            max={10}
            label="Rate the durability of the Vitamix 5200 Blender"
            name="ratingVitamix"
            id="rating-max"
            innerClass="!w-[250px]"
            onItemWrapperClass="!basis-[25px]"
            offItemWrapperClass="!basis-[25px]"
          />
          {/* %partial% */}
          <pre>{JSON.stringify(value, null, 2)}</pre>
        </>
      )}
    </FormKit>
  )
}

// _examples/rating/rating-min-max.vue
<template>
  <!--
  FormKit forms auto-collect values of children inputs.
  Wrap the example in a form so we can display the form values.
-->
  <FormKit type="form" #default="{ value }" :actions="false">
    <!-- %partial%::html:: -->
    <FormKit
      type="rating"
      :min="1"
      :max="10"
      label="Rate the durability of the Vitamix 5200 Blender"
      name="ratingVitamix"
      id="rating-max"
      inner-class="!w-[250px]"
      on-item-wrapper-class="!basis-[25px]"
      off-item-wrapper-class="!basis-[25px]"
    />
    <!-- %partial%::html:: -->
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>
