// _examples/togglebuttons/togglebuttons-single-slots.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <FormKit type="form" actions={false}>
      {/* %partial% */}
      <FormKit type="togglebuttons">Airplane mode</FormKit>

      <FormKit
        type="togglebuttons"
        slots={{
          on: () => (
            <>
              <span className="text-xl">&#9745;</span> Enabled
            </>
          ),
          off: () => (
            <>
              <span className="text-xl">&#9744;</span> Disabled
            </>
          ),
        }}
      />
      {/* %partial% */}
    </FormKit>
  )
}

// .examples/togglebuttons/togglebuttons-single-slots.vue
<template>
  <!--
    FormKit forms auto-collect values of children inputs.
    Wrap the example in a form so we can display the form values.
  -->
  <FormKit type="form" :actions="false">
    <!-- %partial%::html:: -->
    <FormKit type="togglebuttons"> Airplane mode </FormKit>

    <FormKit type="togglebuttons">
      <template #on> &#9745; Enabled </template>
      <template #off> &#9744; Disabled </template>
    </FormKit>
    <!-- %partial%::html:: -->
  </FormKit>
</template>
