// _examples/node-get/node-get.react.jsx
/* %partial% */
import { getNode } from '@formkit/core'
import { useEffect } from 'react'
import { FormKit } from '@formkit/react'

function NodeGetExample() {
  useEffect(() => {
    const node = getNode('manufacturer')
    node?.input('Samsung', false)
  }, [])

  return (
    <FormKit
      type="select"
      id="manufacturer"
      label="Manufacturer"
      options={['Sony', 'Apple', 'Samsung', 'Lenovo']}
      help="Select your favorite tech manufacturer."
    />
  )
}
/* %partial% */

export default function App() {
  return <NodeGetExample />
}

// examples/node-get/node-get.vue
<template>
  <FormKit
    type="select"
    id="manufacturer"
    label="Manufacturer"
    :options="['Sony', 'Apple', 'Samsung', 'Lenovo']"
    help="Select your favorite tech manufacturer."
  />
</template>

<script>
export default {
  mounted() {
    const node = this.$formkit.get('manufacturer')
    node.input('Samsung', false)
  },
}
</script>
