// .examples/node-get/node-get.vue
<script setup>
import { onMounted } from 'vue'
import { getNode } from '@formkit/core'

onMounted(() => {
  const node = getNode('manufacturer')
  node.input('Samsung', false)
})
</script>

<template>
  <FormKit
    type="select"
    id="manufacturer"
    label="Manufacturer"
    :options="['Sony', 'Apple', 'Samsung', 'Lenovo']"
    help="Select your favorite tech manufacturer."
  />
</template>

// _examples/node-get/node-get.react.jsx
/* %partial% */
import { getNode } from '@formkit/core'
import { useEffect } from 'react'
import { FormKit } from '@formkit/react'

function NodeGetExample() {
  useEffect(() => {
    const node = getNode('manufacturer')
    node?.input('Samsung', false)
  }, [])

  return (
    <FormKit
      type="select"
      id="manufacturer"
      label="Manufacturer"
      options={['Sony', 'Apple', 'Samsung', 'Lenovo']}
      help="Select your favorite tech manufacturer."
    />
  )
}
/* %partial% */

export default function App() {
  return <NodeGetExample />
}
