// _examples/classes-config-schema/classes-config-schema.vue
<script setup>
import { FormKitSchema } from '@formkit/vue'

const schema = [
  {
    $formkit: 'group',
    name: 'group',
    // adds 'half' class to all children
    config: { outerClass: 'half' },
    children: [
      {
        $formkit: 'email',
        label: 'Email',
      },
      {
        $formkit: 'email',
        label: "Your spouse's email",
      },
    ]
  }
]
</script>

<template>
  <div class="wrapper">
    <FormKitSchema
      :schema="schema"
    />
  </div>
</template>

<style>
.wrapper { display: flex; }
.half { flex: 0 0 50%; padding-right: 20px; }
</style>

// _examples/classes-config-schema/classes-config-schema.react.jsx
/* %partial% */
import { FormKitSchema } from '@formkit/react'

const schema = [
  {
    $formkit: 'group',
    name: 'group',
    config: { outerClass: 'half' },
    children: [
      {
        $formkit: 'email',
        label: 'Email',
      },
      {
        $formkit: 'email',
        label: "Your spouse's email",
      },
    ],
  },
]

function ClassesConfigSchemaExample() {
  return (
    <>
      <div className="wrapper">
        <FormKitSchema schema={schema} />
      </div>

      <style>{`
        .wrapper {
          display: flex;
        }

        .half {
          flex: 0 0 50%;
          padding-right: 10px;
        }
      `}</style>
    </>
  )
}
/* %partial% */

export default function App() {
  return <ClassesConfigSchemaExample />
}
