// _examples/hidden/hidden-cast.react.jsx
import { FormKit } from '@formkit/react'

export default function App() {
  return (
    <FormKit type="form" actions={false}>
      {({ value }) => (
        <>
          {/* %partial% */}
          <FormKit
            type="hidden"
            number="integer"
            name="account_id"
            value="98213321"
          />
          <pre>{JSON.stringify(value, null, 2)}</pre>
          {/* %partial% */}
        </>
      )}
    </FormKit>
  )
}

// _examples/hidden/hidden-cast.vue
<template>
  <FormKit type="form" :actions="false" #default="{ value }">
    <!-- %partial%::html:: -->
    <FormKit
      type="hidden"
      number="integer"
      name="account_id"
      value="98213321"
    />
    <pre wrap>{{ JSON.stringify(value) }}</pre>
    <!-- %partial%::html:: -->
  </FormKit>
</template>
