// _examples/schema-data/schema-data.vue
<script setup>
import { reactive } from 'vue'

const schema = [
  {
    $el: 'h1',
    children: [
      'Hello ',
      '$location'
    ],
    attrs: {
      class: 'text-2xl font-bold mb-4'
    }
  }
]

const data = reactive({
  location: 'World'
})

const move = () => {
  data.location = data.location === 'World' ? 'Mars' : 'World'
}
</script>

<template>
  <FormKitSchema
    :schema="schema"
    :data="data"
  />
  <FormKit type="button" @click="move">
    Change location
  </FormKit>
</template>

// _examples/schema-data/schema-data.react.jsx
// %partial%
import { useState } from 'react'
import { FormKit, FormKitSchema } from '@formkit/react'

const schema = [
  {
    $el: 'h1',
    children: ['Hello ', '$location'],
    attrs: {
      class: 'text-2xl font-bold mb-4',
    },
  },
]

function Example() {
  const [location, setLocation] = useState('World')
  const data = { location }

  function move() {
    setLocation((current) => (current === 'World' ? 'Mars' : 'World'))
  }

  return (
    <>
      <FormKitSchema schema={schema} data={data} />
      <FormKit type="button" onClick={move}>
        Change location
      </FormKit>
    </>
  )
}
// %partial%

export default function App() {
  return <Example />
}
