// _examples/datetime-local-example/datetime-local-example.react.jsx
import { FormKit } from '@formkit/react'

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit
        type="datetime-local"
        value="2020-03-13T18:22"
        label="End of the world"
        help="When will the end of the world take place?"
        validation="required|date_after"
        validationVisibility="live"
      />
      {/* %partial% */}
    </>
  )
}

// examples/datetime-local-example/datetime-local-example.vue
<template>
  <!-- %partial%::html:: -->
  <FormKit
    type="datetime-local"
    value="2020-03-13T18:22"
    label="End of the world"
    help="When will the end of the world take place?"
    validation="required|after"
    validation-visibility="live"
  />
  <!-- %partial%::html:: -->
</template>
