// .examples/list/list-dynamic-v-model.vue
<script setup>
import { ref } from 'vue'
import { FormKitIcon } from '@formkit/vue'
import { vAutoAnimate } from '@formkit/auto-animate'

const todos = ref([
  'Buy groceries',
  'Do laundry',
  'Clean the bathroom',
  'Pay bills',
  'Call mom',
  'Go for a run',
])
</script>

<template>
  <h1>Todo list</h1>
  <div v-auto-animate>
    <FormKit v-model="todos" type="list" dynamic #default="{ items, value }">
      <div v-for="(item, index) in items" :key="item" class="todo">
        <FormKit type="text" :index="index" />
        <ul class="controls">
          <li>
            <button
              type="button"
              @click="todos.splice(index - 1, 0, todos.splice(index, 1)[0])"
              class="button"
            >
              <FormKitIcon icon="arrowUp" />
            </button>
          </li>
          <li>
            <button
              type="button"
              @click="todos.splice(index + 1, 0, todos.splice(index, 1)[0])"
              class="button"
            >
              <FormKitIcon icon="arrowDown" />
            </button>
          </li>
          <li>
            <button
              type="button"
              @click="todos.splice(index, 1)"
              class="button close"
            >
              <FormKitIcon icon="close" />
            </button>
          </li>
        </ul>
      </div>
      <button type="button" @click="todos.push('')">Add a todo</button>
      <pre wrap>{{ value }}</pre>
    </FormKit>
  </div>
</template>

<style scoped>
.todo {
  display: flex;
  align-items: center;
  margin-bottom: 0.5rem;
}
.todo:deep(.formkit-outer) {
  margin-bottom: 0;
  flex-grow: 1;
}

.controls {
  list-style-type: none;
  margin: 0;
  padding: 0;
  display: flex;
  align-items: center;
}

.controls .button {
  border: none;
  background: none;
  padding: 0;
  margin: 0;
  cursor: pointer;
  color: #999;
  line-height: 1;
  transition: color 0.3s ease;
  appearance: none;
  font-size: 1em;
  color: var(--fk-color-primary);
  margin-left: 0.5rem;
}
.controls:deep(svg) {
  display: block;
  width: 1em;
  max-height: 1.25em;
  height: auto;
  fill: currentColor;
}
.controls .close {
  color: var(--fk-color-danger);
}
</style>

// _examples/list/list-dynamic-v-model.react.jsx
import { useState } from 'react'
import { FormKit, FormKitIcon, defineFormKitConfig } from '@formkit/react'
import { genesisIcons } from '@formkit/icons'

const todoStyle = {
  display: 'flex',
  alignItems: 'center',
  marginBottom: '0.5rem',
}

const controlsStyle = {
  listStyleType: 'none',
  margin: 0,
  padding: 0,
  display: 'flex',
  alignItems: 'center',
}

const buttonStyle = {
  border: 'none',
  background: 'none',
  padding: 0,
  margin: 0,
  cursor: 'pointer',
  lineHeight: 1,
  transition: 'color 0.3s ease',
  appearance: 'none',
  fontSize: '1em',
  color: 'var(--fk-color-primary)',
  marginLeft: '0.5rem',
}

const closeStyle = {
  ...buttonStyle,
  color: 'var(--fk-color-danger)',
}

export const formkitConfig = defineFormKitConfig({
  icons: {
    ...genesisIcons,
  },
})

export default function App() {
  const [todos, setTodos] = useState([
    'Buy groceries',
    'Do laundry',
    'Clean the bathroom',
    'Pay bills',
    'Call mom',
    'Go for a run',
  ])

  function moveTodo(from, to) {
    if (to < 0 || to >= todos.length) return
    const nextTodos = [...todos]
    nextTodos.splice(to, 0, nextTodos.splice(from, 1)[0])
    setTodos(nextTodos)
  }

  return (
    <>
      {/* %partial% */}
      <h1>Todo list</h1>
      <FormKit
        modelValue={todos}
        onUpdateModelValue={setTodos}
        type="list"
        dynamic
        sync
      >
        {({ items, value }) => (
          <>
            {items?.map((item, index) => (
              <div key={`${item}-${index}`} style={todoStyle}>
                <FormKit type="text" index={index} />
                <ul style={controlsStyle}>
                  <li>
                    <button
                      type="button"
                      onClick={() => moveTodo(index, index - 1)}
                      style={buttonStyle}
                    >
                      <FormKitIcon icon="arrowUp" />
                    </button>
                  </li>
                  <li>
                    <button
                      type="button"
                      onClick={() => moveTodo(index, index + 1)}
                      style={buttonStyle}
                    >
                      <FormKitIcon icon="arrowDown" />
                    </button>
                  </li>
                  <li>
                    <button
                      type="button"
                      onClick={() =>
                        setTodos((current) =>
                          current.filter((_, todoIndex) => todoIndex !== index)
                        )
                      }
                      style={closeStyle}
                    >
                      <FormKitIcon icon="close" />
                    </button>
                  </li>
                </ul>
              </div>
            ))}
            <FormKit
              type="button"
              onClick={() => setTodos((current) => current.concat(''))}
            >
              Add a todo
            </FormKit>
            <pre>{JSON.stringify(value, null, 2)}</pre>
          </>
        )}
      </FormKit>
      {/* %partial% */}
    </>
  )
}
