// _examples/custom-props-create-input/custom-props-object-notation.vue
<script setup>
import { createInput } from '@formkit/vue'

const myInput = createInput(
  {
    $el: 'button',
    for: ['option', '$options'],
    attrs: {
      class: '$classes.input',
      placeholder: '$: "Hello " + $location',
      onClick: '$handlers.setValue($option)',
      ariaSelected: '$: $option === $value',
    },
    children: ['$currency', '$option'],
  },
  {
    props: {
      // 👀 A boolean prop — these can be added as attributes to the component
      capitalize: {
        boolean: true,
      },
      // 👀 Here we have a prop with a default value
      currency: {
        default: '',
      },
      // 👀 This prop has a setter that transforms the prop value anytime it is set
      options: {
        setter(value, node) {
          let options
          if (typeof value === 'string') {
            options = value.split(',')
          } else {
            options = value
          }
          if (node.props.capitalize) {
            options = options.map(
              (option) => option[0].toUpperCase() + option.slice(1)
            )
          }
          return options
        },
      },
    },
    features: [
      function setValues(node) {
        node.on('created', () => {
          // Notice the currying here bind the value into the callback
          node.context.handlers.setValue = (value) => () => node.input(value)
        })
      },
    ],
  }
)
</script>

<template>
  <FormKit type="group" #default="{ value }">
    <FormKit
      :type="myInput"
      name="planet"
      label="Select a hospitable planet"
      capitalize
      options="earth,mars,venus"
      input-class="border-2 border-gray-300 mr-2 mb-2 px-2 py-1 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm aria-[selected=true]:bg-gray-200 dark:bg-gray-800 dark:aria-[selected=true]:bg-blue-900 dark:border-gray-700 dark:focus:ring-gray-500 dark:focus:border-gray-500"
    />
    <FormKit
      :type="myInput"
      name="price"
      label="Price"
      currency="$"
      :options="['10.00', '12.99', '15.00']"
      help="How much are you willing to pay?"
      input-class="border-2 border-gray-300 mr-2 mb-2 px-2 py-1 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm aria-[selected=true]:bg-gray-200 dark:bg-gray-800 dark:aria-[selected=true]:bg-blue-900 dark:border-gray-700 dark:focus:ring-gray-500 dark:focus:border-gray-500"
    />
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>

// _examples/custom-props-create-input/custom-props-object-notation.react.jsx
import { useState } from 'react'

/* %partial% */
import { FormKit, createInput } from '@formkit/react'

const myInput = createInput(
  {
    $el: 'button',
    for: ['option', '$options'],
    attrs: {
      class: '$classes.input',
      placeholder: '$: "Hello " + $location',
      onClick: '$handlers.setValue($option)',
      ariaSelected: '$: $option === $value',
    },
    children: ['$currency', '$option'],
  },
  {
    props: {
      capitalize: {
        boolean: true,
      },
      currency: {
        default: '',
      },
      options: {
        setter(value, node) {
          let options
          if (typeof value === 'string') {
            options = value.split(',')
          } else {
            options = value
          }
          if (node.props.capitalize) {
            options = options.map(
              (option) => option[0].toUpperCase() + option.slice(1)
            )
          }
          return options
        },
      },
    },
    features: [
      function setValues(node) {
        node.on('created', () => {
          node.context.handlers.setValue = (value) => () => node.input(value)
        })
      },
    ],
  }
)

function CustomPropsObjectNotationExample() {
  const [value, setValue] = useState({})

  return (
    <>
      <FormKit
        type="group"
        modelValue={value}
        onUpdateModelValue={(nextValue) => setValue(nextValue ?? {})}
      >
        <FormKit
          type={myInput}
          name="planet"
          label="Select a hospitable planet"
          capitalize
          options="earth,mars,venus"
          inputClass="border-2 border-gray-300 mr-2 mb-2 px-2 py-1 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm aria-[selected=true]:bg-gray-200 dark:bg-gray-800 dark:aria-[selected=true]:bg-blue-900 dark:border-gray-700 dark:focus:ring-gray-500 dark:focus:border-gray-500"
        />
        <FormKit
          type={myInput}
          name="price"
          label="Price"
          currency="$"
          options={['10.00', '12.99', '15.00']}
          help="How much are you willing to pay?"
          inputClass="border-2 border-gray-300 mr-2 mb-2 px-2 py-1 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm aria-[selected=true]:bg-gray-200 dark:bg-gray-800 dark:aria-[selected=true]:bg-blue-900 dark:border-gray-700 dark:focus:ring-gray-500 dark:focus:border-gray-500"
        />
      </FormKit>
      <pre>{JSON.stringify(value, null, 2)}</pre>
    </>
  )
}
/* %partial% */

export default function App() {
  return <CustomPropsObjectNotationExample />
}
