// examples/locale-change-config/locale-change-config.vue
%partial%
<template>
  <a @click.prevent="changeLocale" href="#">
    <span v-if="current === 'en'">🇩🇪 config.locale = 'de'</span>
    <span v-if="current === 'de'">🇺🇸 config.locale = 'en'</span>
  </a>
  <FormKit type="form">
    <FormKit
      type="email"
      label="Email"
      placeholder="email@example.com"
      validation="required|email"
    />
  </FormKit>
  <small>
    Note: this example does not contain a full german locale, only the messages
    required for this example (submit, required, email).
  </small>
</template>

<script setup>
import { ref, inject } from 'vue'

const current = ref('en')
const config = inject(Symbol.for('FormKitConfig'))

const changeLocale = () => {
  current.value = current.value === 'en' ? 'de' : 'en'
  config.locale = current.value
}
</script>
%partial%

<style>
a {
  margin-bottom: 2em;
}
small {
  margin-top: 1em;
  color: SlateGray;
}
</style>

// _examples/locale-change-config/locale-change-config.react.jsx
// %partial%
import { useEffect, useState } from 'react'
import { FormKit, changeLocale } from '@formkit/react'
export { default as formkitConfig } from './formkit.config.react.jsx'

const styles = `
  .locale-switch {
    display: inline-block;
    margin-bottom: 2em;
  }

  .locale-note {
    display: block;
    margin-top: 1em;
    color: SlateGray;
  }
`

export default function App() {
  const [current, setCurrent] = useState('en')

  useEffect(() => {
    changeLocale(current)

    return () => {
      changeLocale('en')
    }
  }, [current])

  const toggleLocale = () => {
    setCurrent((locale) => (locale === 'en' ? 'de' : 'en'))
  }

  return (
    <>
      <style>{styles}</style>
      <a
        className="locale-switch"
        onClick={(event) => {
          event.preventDefault()
          toggleLocale()
        }}
        href="#"
      >
        {current === 'en' ? (
          <span>🇩🇪 config.locale = 'de'</span>
        ) : (
          <span>🇺🇸 config.locale = 'en'</span>
        )}
      </a>
      <FormKit type="form" onSubmit={() => false}>
        <FormKit
          type="email"
          label="Email"
          placeholder="email@example.com"
          validation="required|email"
        />
      </FormKit>
      <small className="locale-note">
        Note: this example does not contain a full german locale, only the
        messages required for this example (submit, required, email).
      </small>
    </>
  )
}
// %partial%
