// _examples/password/password.react.jsx
import { FormKit } from '@formkit/react'

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit type="group">
        <h2>Create a new password</h2>
        <FormKit
          type="password"
          name="password"
          value="super-secret"
          label="Password"
          help="Enter a new password"
          validation="required"
          validationVisibility="live"
        />
        <FormKit
          type="password"
          name="password_confirm"
          label="Confirm password"
          help="Confirm your new password"
          validation="required|confirm"
          validationVisibility="live"
          validationLabel="Password confirmation"
        />
      </FormKit>
      {/* %partial% */}
    </>
  )
}

// examples/password/password.vue
<template>
  <!-- %partial%::html:: -->
  <FormKit type="group">
    <h2>Create a new password</h2>
    <FormKit
      type="password"
      name="password"
      value="super-secret"
      label="Password"
      help="Enter a new password"
      validation="required"
      validation-visibility="live"
    />
    <FormKit
      type="password"
      name="password_confirm"
      label="Confirm password"
      help="Confirm your new password"
      validation="required|confirm"
      validation-visibility="live"
      validation-label="Password confirmation"
    />
  </FormKit>
  <!-- %partial%::html:: -->
</template>
