// _examples/meta/meta.react.jsx
import { FormKit } from '@formkit/react'

const extraData = {
  hair: 'gold',
  eyes: 'blue',
  weight: '215lb',
  height: '6ft 3in',
  hands: 'tiny',
  cool: false,
}

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit type="form" actions={false}>
        {({ value }) => (
          <>
            <FormKit name="name" label="Name" />
            <FormKit type="meta" name="metaDetails" value={extraData} />
            <pre>{JSON.stringify(value, null, 2)}</pre>
          </>
        )}
      </FormKit>
      {/* %partial% */}
    </>
  )
}

// _examples/meta/meta.vue
<script setup>
import { ref } from 'vue'

const extraData = {
  hair: 'gold',
  eyes: 'blue',
  weight: '215lb',
  height: '6ft 3in',
  hands: 'tiny',
  cool: false
}
</script>

<template>
  <FormKit type="form" :actions="false" #default="{ value }">
    <FormKit name="name" label="Name" />
    <FormKit type="meta" name="metaDetails" :value="extraData" />
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>
