// _examples/slider/linked-inputs.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit
        type="slider"
        defaultValue={33}
        label="A single slider with a visible input"
        help="I have a single linked input"
        showInput
      />

      <FormKit
        type="slider"
        defaultValue={[33, 66]}
        label="A slider with multiple inputs"
        showInput
      />
      {/* %partial% */}
    </>
  )
}

// _examples/slider/linked-inputs.vue
<template>
  <!-- %partial%::html:: -->
  <FormKit
    type="slider"
    value="33"
    label="A single slider with a visible input"
    help="I have a single linked input"
    :show-input="true"
  />

  <FormKit
    type="slider"
    :value="[33, 66]"
    label="A slider with multiple inputs"
    :show-input="true"
  />
  <!-- %partial%::html:: -->
</template>
