// _examples/form/form-validity.react.jsx
/* %partial% */
import { FormKit } from '@formkit/react'

function handleSubmit() {
  alert('Password reset!')
}

function FormValidityExample() {
  return (
    <FormKit type="form" actions={false} onSubmit={handleSubmit}>
      {({ state: { valid } }) => (
        <>
          <h2 className="text-xl font-bold mb-4">Password reset</h2>
          <FormKit
            type="email"
            label="Email address"
            help="Enter your email address to reset your password"
            validation="required|email"
          />
          <FormKit type="submit" disabled={!valid} />
          <pre>{`Form validity: ${String(valid)}`}</pre>
        </>
      )}
    </FormKit>
  )
}
/* %partial% */

export default function App() {
  return <FormValidityExample />
}

// .examples/form-validity/form-validity.vue
<script setup>
const handleSubmit = () => alert('Password reset!')
</script>

<template>
  <FormKit
    type="form"
    :actions="false"
    @submit="handleSubmit"
    #default="{ state: { valid } }"
  >
    <h2 class="text-xl font-bold mb-4">Password reset</h2>
    <FormKit
      type="email"
      label="Email address"
      help="Enter your email address to reset your password"
      validation="required|email"
    />
    <FormKit type="submit" :disabled="!valid" />
    <pre wrap>Form validity: {{ valid }}</pre>
  </FormKit>
</template>
