// examples/custom-sum/custom-sum.vue
<template>
  <FormKit type="group" v-model="groupValues">
    <p>
      To illustrate the final value of this input, let's stick it in a group.
    </p>
    <FormKit
      :type="sum"
      name="mySum"
      label="Sum 2 numbers"
      help="Enter two numbers above and their values will be summed!"
    />
  </FormKit>
  <pre wrap>{{ groupValues }}</pre>
</template>

<script setup>
import { ref } from 'vue'
import { createInput } from '@formkit/vue'

// Here's our schema, notice we have 2 handlers:
// numberA and numberB. Those are not provided by FormKit by default, they are
// defined in our "feature".
const sum = createInput(
  [
    {
      $el: 'input',
      attrs: {
        class: '$classes.addend',
        type: 'number',
        onInput: '$handlers.numberA',
      },
    },
    '+',
    {
      $el: 'input',
      attrs: {
        class: '$classes.addend',
        type: 'number',
        onInput: '$handlers.numberB',
      },
    },
    '= ',
    '$_value || 0',
  ],
  {
    features: [addHandlers],
  }
)

/**
 * Here we add our handlers.
 */
function addHandlers(node) {
  // Features are run very early in the node’s boot — before the context object
  // is fully initialized, so we wait till the node is "created" — this is still
  // before the node is mounted, but after plugins have run.
  let numberA = 0
  let numberB = 0

  node.on('created', () => {
    // Now we define a new handler. Note that context.handlers is the same
    // object available in $handlers in our schema.
    node.context.handlers.numberA = (event) => {
      numberA = Number(event.target.value)
      // We update the value of the input by calling node.input()
      node.input(numberA + numberB)
    }

    // Now a second context handler
    node.context.handlers.numberB = (event) => {
      numberB = Number(event.target.value)
      node.input(numberA + numberB)
    }
  })
}

const groupValues = ref({})
</script>

<style>
.formkit-addend {
  border: 0;
  background-color: #efefef;
  margin: 0 0.25em;
  width: 4em;
  padding: 0.5em;
}
.formkit-addend:first-child {
  margin-left: 0;
  border-radius: 0.25em 0 0 0.25em;
}
.formkit-addend:focus {
  outline: 0;
}
</style>

// _examples/custom-sum/custom-sum.react.jsx
import { useState } from 'react'

export { default as formkitConfig } from './formkit.config.react.jsx'
/* %partial% */
import { FormKit, createInput } from '@formkit/react'

const sum = createInput(
  [
    {
      $el: 'input',
      attrs: {
        class: '$classes.addend',
        type: 'number',
        onInput: '$handlers.numberA',
      },
    },
    '+',
    {
      $el: 'input',
      attrs: {
        class: '$classes.addend',
        type: 'number',
        onInput: '$handlers.numberB',
      },
    },
    '= ',
    '$_value || 0',
  ],
  {
    features: [addHandlers],
    family: 'text',
  }
)

function addHandlers(node) {
  let numberA = 0
  let numberB = 0

  node.on('created', () => {
    node.context.handlers.numberA = (event) => {
      numberA = Number(event.target.value)
      node.input(numberA + numberB)
    }

    node.context.handlers.numberB = (event) => {
      numberB = Number(event.target.value)
      node.input(numberA + numberB)
    }
  })
}

function CustomSumExample() {
  const [groupValues, setGroupValues] = useState({})

  return (
    <>
      <FormKit
        type="group"
        modelValue={groupValues}
        onUpdateModelValue={(value) => setGroupValues(value ?? {})}
      >
        <p className="mb-4">
          To illustrate the final value of this input, let&apos;s stick it in a
          group.
        </p>
        <FormKit
          type={sum}
          name="mySum"
          label="Sum 2 numbers"
          help="Enter two numbers above and their values will be summed!"
        />
      </FormKit>
      <pre>{JSON.stringify(groupValues, null, 2)}</pre>
    </>
  )
}
/* %partial% */

export default function App() {
  return <CustomSumExample />
}
