// examples/node-ref/node-ref.vue
<script setup>
import { ref } from 'vue'
const myInput = ref(null)

const setEmail = () => {
  myInput.value.node.input('djokovic@tennis.gov')
}
</script>

<template>
  <FormKit ref="myInput" label="Email address" />
  <FormKit type="button" @click="setEmail" label="Click to set email" />
</template>

// _examples/node-ref/node-ref.react.jsx
/* %partial% */
import { useRef } from 'react'
import { FormKit } from '@formkit/react'

function NodeRefExample() {
  const myInput = useRef(null)

  function setEmail() {
    myInput.current?.input('djokovic@tennis.gov')
  }

  return (
    <>
      <FormKit ref={myInput} label="Email address" />
      <FormKit type="button" onClick={setEmail} label="Click to set email" />
    </>
  )
}
/* %partial% */

export default function App() {
  return <NodeRefExample />
}
