// .examples/barcode/basic.vue
<template>
  <!-- %partial% -->
  <FormKit
    type="barcode"
    label="Barcode"
    help="Please scan a barcode"
  />
  <!-- %partial% -->
</template>

<style>
/* this import is only neccessary for the playground */
@import "https://cdn.jsdelivr.net/npm/@formkit/barcode@latest/dist/assets/barcodeReader.css";
</style>

// _examples/barcode/basic.react.jsx
import { FormKit } from '@formkit/react'
export { default as formkitConfig } from './formkit.config.react.jsx'

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit type="barcode" label="Barcode" help="Please scan a barcode" />
      {/* %partial% */}
    </>
  )
}
