// examples/form-errors/form-errors.vue
<template>
  <!-- %partial%::html -->
  <FormKit
    type="form"
    submit-label="Login"
    :errors="['Sorry, our server is currently down. Please try again soon.']"
  >
    <FormKit type="email" label="Email address" />
    <FormKit type="password" label="Password" />
  </FormKit>
  <!-- %partial%::html -->
</template>

// _examples/form/form-errors.react.jsx
import { FormKit } from '@formkit/react'

function FormErrorsExample() {
  return (
    <>
      {/* %partial% */}
      <FormKit
        type="form"
        onSubmit={() => false}
        submitLabel="Login"
        errors={['Our server is not working.', "But we don't like you anyway!"]}
      >
        <FormKit type="email" label="Email address" />
        <FormKit type="password" label="Password" />
      </FormKit>
      {/* %partial% */}
    </>
  )
}

export default function App() {
  return <FormErrorsExample />
}
