// examples/form-xhr/form-xhr.vue
<!-- %partial% -->
<script>
// This is just a mock of an actual axios instance.
const axios = {
  post: () => new Promise(r => setTimeout(r, 2000))
}
</script>

<template>
  <FormKit
    type="form"
    submit-label="Login"
    @submit="login"
  >
    <FormKit
      name="email"
      label="Email address"
      validation="required|email"
    />
    <FormKit
      type="password"
      name="password"
      label="Password"
      validation="required"
    />
  </FormKit>
</template>

// _examples/form/form-xhr.react.jsx
/* %partial% */
import { FormKit } from '@formkit/react'

const axios = {
  post: () => new Promise((resolve) => setTimeout(resolve, 2000)),
}

async function login(credentials) {
  await axios.post(credentials)
  alert('Logged in!')
}

function FormXhrExample() {
  return (
    <FormKit type="form" submitLabel="Login" onSubmit={login}>
      <FormKit name="email" label="Email address" validation="required|email" />
      <FormKit
        type="password"
        name="password"
        label="Password"
        validation="required"
      />
    </FormKit>
  )
}
/* %partial% */

export default function App() {
  return <FormXhrExample />
}
