// _examples/preserve-errors-config/preserve-errors-config.vue
<script>
export default {
  mounted() {
    this.$formkit.setErrors('register', [], {
      username: 'That username is taken.',
      password: 'Your password is too simple.',
    })
  },
}
</script>

<template>
  <!-- %partial%::html:: -->
  <FormKit
    type="form"
    @submit="() => false"
    id="register"
    :config="{ preserveErrors: true }"
  >
    <FormKit
      name="username"
      label="Username"
      help="Select a new username"
    />
    <FormKit
      name="password"
      label="Password"
    />
  </FormKit>
  <!-- %partial%::html:: -->
</template>

// _examples/form/preserve-errors-config.react.jsx
import { FormKit, setErrors } from '@formkit/react'
import { useEffect } from 'react'

function PreserveErrorsConfigExample() {
  useEffect(() => {
    setErrors('register', [], {
      username: 'That username is taken.',
      password: 'Your password is too simple.',
    })
  }, [])

  return (
    <>
      {/* %partial% */}
      <FormKit
        type="form"
        onSubmit={() => false}
        id="register"
        config={{ preserveErrors: true }}
      >
        <FormKit
          name="username"
          label="Username"
          help="Select a new username"
        />
        <FormKit name="password" label="Password" />
      </FormKit>
      {/* %partial% */}
    </>
  )
}

export default function App() {
  return <PreserveErrorsConfigExample />
}
