// examples/set-errors/set-errors.vue
<template>
  <FormKit
    type="form"
    id="order-form"
    submit-label="Order chips"
    @submit="order"
  >
    <h2>Bulk order</h2>
    <FormKit
      type="select"
      name="flavor"
      label="Chip flavor"
      validation="required"
      :options="{
        bbq: 'Barbecue',
        pickle: 'Dill pickle',
        habanero: 'Habanero',
        boring: 'Original',
        vinegar: 'Salt & Vinegar',
      }"
    />
    <FormKit
      type="number"
      step="1"
      name="quantity"
      label="Quantity"
      value="500"
      validation="required|min:100"
      :validation-messages="{
        min: 'Minimum order is 100 units.',
      }"
    />
  </FormKit>
</template>

<script>
export default {
  methods: {
    async order(data) {
      try {
        await fakeApiCall(data)
      } catch (inputErrors) {
        this.$formkit.setErrors(
          'order-form', // You must use the ID of the form
          ['There was an error with your order!'], // (optional) An array of form level errors
          inputErrors // (optional) input level errors
        )
      }
    },
  },
}

/**
 * This is just to illustrate how you might handle an XHR call with fetch or
 * with axios.
 */
function fakeApiCall(data) {
  return new Promise((_, reject) => {
    setTimeout(
      () =>
        reject({
          flavor: 'Sorry, that type is now sold out!',
        }),
      1000
    )
  })
}
</script>

// _examples/form/set-errors.react.jsx
/* %partial% */
import { FormKit, setErrors } from '@formkit/react'

async function order(data) {
  try {
    await fakeApiCall(data)
  } catch (inputErrors) {
    setErrors(
      'order-form',
      ['There was an error with your order!'],
      inputErrors
    )
  }
}

function fakeApiCall() {
  return new Promise((_, reject) => {
    setTimeout(
      () =>
        reject({
          flavor: 'Sorry, that type is now sold out!',
        }),
      1000
    )
  })
}

function SetErrorsExample() {
  return (
    <FormKit
      type="form"
      id="order-form"
      submitLabel="Order chips"
      onSubmit={order}
    >
      <h2 className="text-xl font-bold mb-4">Bulk order</h2>
      <FormKit
        type="select"
        name="flavor"
        label="Chip flavor"
        validation="required"
        options={{
          bbq: 'Barbecue',
          pickle: 'Dill pickle',
          habanero: 'Habanero',
          boring: 'Original',
          vinegar: 'Salt & Vinegar',
        }}
      />
      <FormKit
        type="number"
        step="1"
        name="quantity"
        label="Quantity"
        value="500"
        validation="required|min:100"
        validationMessages={{
          min: 'Minimum order is 100 units.',
        }}
      />
    </FormKit>
  )
}
/* %partial% */

export default function App() {
  return <SetErrorsExample />
}
