// _examples/multi-step/tab-style/multi-step-content.vue
<template>
  <FormKit type="step" name="stepOne">
    <FormKit type="text" label="Name" validation="required" />
  </FormKit>
  <FormKit type="step" name="stepTwo">
    <FormKit type="textarea" label="Your story" validation="required" />
  </FormKit>
  <FormKit type="step" name="stepThree">
    <FormKit type="textarea" label="Something else" validation="required" />
  </FormKit>
</template>

// _examples/multi-step/tab-style/multi-step-content.react.jsx
import { FormKit } from '@formkit/react'

export default function MultiStepContent() {
  return (
    <>
      <FormKit type="step" name="stepOne">
        <FormKit type="text" label="Name" validation="required" />
      </FormKit>
      <FormKit type="step" name="stepTwo">
        <FormKit type="textarea" label="Your story" validation="required" />
      </FormKit>
      <FormKit type="step" name="stepThree">
        <FormKit type="textarea" label="Something else" validation="required" />
      </FormKit>
    </>
  )
}
