// examples/multi-step/tab-style/tab-style.vue
<script setup>
import MultiStepContent from './multi-step-content.vue'
</script>

<template>
  <!-- %partial% -->
  <!-- default tab style -->
  <FormKit type="multi-step" tab-style="tab">
    <MultiStepContent />
  </FormKit>

  <!-- progress tab style -->
  <FormKit type="multi-step" tab-style="progress">
    <MultiStepContent />
  </FormKit>

  <!-- progress tab style w/ hidden labels -->
  <FormKit type="multi-step" tab-style="progress" :hide-progress-labels="true">
    <MultiStepContent />
  </FormKit>
  <!-- %partial% -->
</template>

// _examples/multi-step/tab-style/tab-style.react.jsx
import { FormKit } from '@formkit/react'
export { default as formkitConfig } from '../formkit.config.react.jsx'
import MultiStepContent from './multi-step-content.react.jsx'

export default function App() {
  return (
    <>
      {/* %partial% */}
      {/* default tab style */}
      <FormKit type="multi-step" tabStyle="tab">
        <MultiStepContent />
      </FormKit>

      {/* progress tab style */}
      <FormKit type="multi-step" tabStyle="progress">
        <MultiStepContent />
      </FormKit>

      {/* progress tab style w/ hidden labels */}
      <FormKit type="multi-step" tabStyle="progress" hideProgressLabels={true}>
        <MultiStepContent />
      </FormKit>
      {/* %partial% */}
    </>
  )
}
