// _examples/schema-overrides/schema-overrides.react.jsx
import { FormKit } from '@formkit/react'

function SchemaOverridesExample() {
  return (
    <>
      {/* %partial% */}
      <FormKit
        label="Full name"
        help="Please provide your full name."
        sectionsSchema={{
          messages: { $el: 'div' },
          message: { $el: 'span' },
        }}
        validation="required|length:5"
        validationVisibility="live"
      />
      {/* Remove the sectionsSchema prop to see validation
          messages revert to their default HTML. */}
      {/* %partial% */}
    </>
  )
}

export default function App() {
  return <SchemaOverridesExample />
}

// _examples/schema-overrides/schema-overrides.vue
<template>
  <!-- %partial%::html:: -->
  <FormKit
    label="Full name"
    help="Please provide your full name."
    :sections-schema="{
      messages: { $el: 'div' },
      message: { $el: 'span' },
    }"
    validation="required|length:5"
    validation-visibility="live"
  />
  <!-- Remove the :sections-schema prop to see validation
        messages revert to their default HTML. -->
  <!-- %partial%::html:: -->
</template>
