// _examples/taglist/taglist-allow-new-values.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

// %partial%
const flavors = ['Chocolate', 'Vanilla', 'Strawberry']

function TaglistExample() {
  return (
    <FormKit type="form" actions={false}>
      {({ value }) => (
        <>
          <FormKit
            type="taglist"
            name="flavors"
            label="Select or add a flavor"
            popover
            options={flavors}
            defaultValue={['Chocolate', 'Vanilla']}
            allowNewValues
          />
          <pre>{JSON.stringify(value, null, 2)}</pre>
        </>
      )}
    </FormKit>
  )
}
// %partial%

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return <TaglistExample />
}

// examples/taglist/taglist-allow-new-values.vue
<script setup>
const flavors = ['Chocolate', 'Vanilla', 'Strawberry'];
</script>

<template>
  <FormKit
    type="form"
    #default="{ value }"
    :actions="false"
  >
    <FormKit
      type="taglist"
      name="flavors"
      label="Select or add a flavor"
      :options="flavors"
      :value="['Chocolate', 'Vanilla']"
      :allow-new-values="true"
    />
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>
