// examples/submit/submit-events.vue
<script setup>
const randomColor = (e) => {
  const hex = Math
    .floor(Math.random()*16777215)
    .toString(16)
  e.target.setAttribute(
    'style',
    'background-color: #' + hex
  )
}
</script>

<template>
  <FormKit
    type="submit"
    help="You can bind event listeners."
    @click="randomColor"
  >
    Click me!
  </FormKit>
</template>

// _examples/submit/submit-events.react.jsx
import { FormKit } from '@formkit/react'

function randomColor(event) {
  const hex = Math.floor(Math.random() * 16777215).toString(16)
  event.currentTarget.setAttribute('style', `background-color: #${hex};`)
}

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit
        type="submit"
        help="You can bind event listeners."
        onClick={randomColor}
      >
        Click me!
      </FormKit>
      {/* %partial% */}
    </>
  )
}
