// _examples/taglist/taglist-open-on-remove.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

// %partial%
import countries from '../_data/countries.js'

function TaglistExample() {
  return (
    <FormKit
      type="taglist"
      name="country"
      label="Search for a country"
      placeholder="Example: United States"
      options={countries}
      openOnRemove
      popover
      defaultValue={['US']}
    />
  )
}
// %partial%

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return <TaglistExample />
}

// _examples/taglist/taglist-open-on-remove.vue
<script setup>
import countries from '@content/_examples/_data/countries.js'
</script>

<template>
	<FormKit
		type="taglist"
		name="country"
		label="Search for a country"
		placeholder="Example: United States"
		:options="countries"
		open-on-remove
		popover
		:value="['US']"
	/>
	<pre wrap>{{ value }}</pre>
</template>
