// _examples/unit/unit-display.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: {
    ...genesisIcons,
  },
})

export default function App() {
  return (
    <FormKit type="form" actions={false}>
      {/* %partial% */}
      <FormKit
        type="unit"
        unit="kilogram"
        name="narrow"
        unitDisplay="narrow"
        label="Narrow"
        defaultValue={100}
      />
      <FormKit
        type="unit"
        unit="kilogram"
        name="short"
        unitDisplay="short"
        label="Short"
        defaultValue={100}
      />
      <FormKit
        type="unit"
        unit="kilogram"
        name="long"
        unitDisplay="long"
        label="Long"
        defaultValue={100}
      />
      {/* %partial% */}
    </FormKit>
  )
}

// .examples/unit/unit-display.vue
<script setup>
const initialValues = {
  narrow: 100,
  short: 100,
  long: 100,
  empty: 100,
}
</script>

<template>
  <FormKit type="form" :actions="false" :value="initialValues">
    <!-- %partial%::html:: -->
    <FormKit
      type="unit"
      unit="kilogram"
      name="narrow"
      unit-display="narrow"
      label="Narrow"
    />
    <FormKit
      type="unit"
      unit="kilogram"
      name="short"
      unit-display="short"
      label="Short"
    />
    <FormKit
      type="unit"
      unit="kilogram"
      name="long"
      unit-display="long"
      label="Long"
    />
    <!-- %partial%::html:: -->
  </FormKit>
</template>
