// examples/formkit-messages/normal-input.vue
<!-- %partial%:html -->
<script setup>
import { ref } from 'vue'
import { FormKitMessages } from '@formkit/vue'
const input = ref()
</script>

<template>
  <div class="flex">
    <FormKit
      type="text"
      ref="input"
      validation="required|length:4"
      validation-visibility="live"
      label="Dinosaur name"
      placeholder="Stegosaurus"
    />
    <!-- 👀 messages will be rendered here instead -->
    <FormKitMessages :node="input?.node" />
  </div>
</template>
<!-- %partial%:html -->

<style scoped>
.flex {
  display: flex;
  gap: 1rem;
}
</style>

// _examples/formkit-messages/normal-input.react.jsx
/* %partial% */
import { useState } from 'react'
import { FormKit, FormKitMessages } from '@formkit/react'

function NormalInputMessagesExample() {
  const [inputNode, setInputNode] = useState(undefined)

  return (
    <div style={{ display: 'flex', gap: '1rem' }}>
      <FormKit
        type="text"
        onNode={setInputNode}
        validation="required|length:4"
        validationVisibility="live"
        label="Dinosaur name"
        placeholder="Stegosaurus"
      />
      {/* messages will be rendered here instead */}
      <FormKitMessages node={inputNode} />
    </div>
  )
}
/* %partial% */

export default function App() {
  return <NormalInputMessagesExample />
}
