// examples/simple-errors/simple-errors.vue
<script setup>
import { ref, computed } from 'vue'
const fruit = ref('')
const errors = computed(() => {
  return fruit.value ? [`Sorry, we are sold out of ${fruit.value}`] : []
})
</script>

<template>
  <FormKit
    type="select"
    label="Fruit"
    placeholder="Select a fruit"
    v-model="fruit"
    :options="['Apple', 'Peach', 'Pear']"
    :errors="errors"
  />
</template>

// _examples/simple-errors/simple-errors.react.jsx
/* %partial% */
import { useState } from 'react'
import { FormKit } from '@formkit/react'
/* %partial% */

/* %partial% */
function SimpleErrorsExample() {
  const [fruit, setFruit] = useState('')
  const errors = fruit ? [`Sorry, we are sold out of ${fruit}`] : []

  return (
    <FormKit
      type="select"
      label="Fruit"
      placeholder="Select a fruit"
      modelValue={fruit}
      onUpdateModelValue={setFruit}
      options={['Apple', 'Peach', 'Pear']}
      errors={errors}
    />
  )
}
/* %partial% */

export default function App() {
  return <SimpleErrorsExample />
}
