// _examples/schema-wrappers/schema-wrappers.react.jsx
import { FormKit } from '@formkit/react'

function SchemaWrappersExample() {
  return (
    <>
      {/* %partial% */}
      <FormKit
        type="checkbox"
        sectionsSchema={{
          outer: { $el: null },
          inner: { $el: null },
          messages: { $el: null },
          message: { $el: 'div' },
        }}
        validation="+accepted"
        validationVisibility="live"
        label="Terms and conditions"
        help="Do you accept our terms and conditions?"
      />
      {/* Remove the "inner" property of the schema object
          and see the inner wrapper reappear. */}
      {/* %partial% */}
    </>
  )
}

export default function App() {
  return <SchemaWrappersExample />
}

// examples/schema-wrappers/schema-wrappers.vue
<template>
<!-- %partial%::html:: -->
<FormKit
  type="checkbox"
  :schema="{
    outer: { $el: null },
    inner: { $el: null },
    messages: { $el: null },
    message: { $el: 'div' },
  }"
  validation="+accepted"
  validation-behavior="live"
  label="Terms and conditions"
  help="Do you accept our terms and conditions?"
/>
<!-- Remove the "inner" property of the schema object
      and see the inner wrapper reappear. -->
<!-- %partial%::html:: -->
</template>
