// .examples/rule-date-after/rule-date-after.vue
<template>
  <!-- %partial%::html:: -->
  <FormKit
    type="date"
    label="Birthday"
    help="Enter your birthday (must be born after 1999)"
    validation="date_after:1999-12-31"
    validation-visibility="live"
    :validation-messages="{
      date_after: 'Sorry — no olds allowed.',
    }"
    value="1988-05-14"
  />
  <!-- %partial%::html:: -->
</template>

// _examples/rule-date-after/rule-date-after.react.jsx
import { FormKit } from '@formkit/react'

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit
        type="date"
        label="Birthday"
        help="Enter your birthday (must be born after 1999)"
        validation="date_after:1999-12-31"
        validationVisibility="live"
        validationMessages={{
          date_after: 'Sorry - no olds allowed.',
        }}
        value="1988-05-14"
      />
      {/* %partial% */}
    </>
  )
}
