// examples/guides/your-first-form/character-group-attributes/example.vue
<script setup>
const castRangeToNumber = (node) => {
  // We add a check to add the cast only to range inputs
  if (node.props.type !== 'range') return

  node.hook.input((value, next) => next(Number(value)))
}

const createCharacter = async (fields) => {
  await new Promise((r) => setTimeout(r, 1000))
  alert(JSON.stringify(fields))
}
</script>

<!-- %partial%::html:: -->
<template>
  <h1>New Character</h1>

  <!-- form is also an input, so it also accepts plugins -->
  <FormKit
    type="form"
    @submit="createCharacter"
    :plugins="[castRangeToNumber]"
    submit-label="Create Character"
    #default="{ value }"
  >
    <FormKit
      type="text"
      name="name"
      id="name"
      validation="required|not:Admin"
      label="Name"
      help="Your full name"
      placeholder="Please add your name"
    />

    <FormKit
      type="select"
      name="class"
      label="Class"
      id="class"
      :options="['Warrior', 'Mage', 'Assassin']"
    />

    <FormKit type="group" name="attributes" id="attributes">
      <FormKit
        type="range"
        name="skill"
        id="skill"
        label="Skill"
        value="5"
        min="1"
        max="10"
        step="1"
        help="How much skill points to start with"
      />

      <FormKit
        type="range"
        name="strength"
        id="strength"
        label="Strength"
        value="5"
        min="1"
        max="10"
        step="1"
        help="How much strength points to start with"
      />

      <FormKit
        type="range"
        name="dexterity"
        id="dexterity"
        label="Dexterity"
        value="5"
        min="1"
        max="10"
        step="1"
        help="How many dexterity points should this character have?"
      />
    </FormKit>
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>
<!-- %partial%::html:: -->

<style>
pre[wrap] {
  margin-bottom: 20px !important;
}
</style>

// _examples/guides/your-first-form/character-attributes-update/example.react.jsx
/* %partial% */
import { useEffect } from 'react'
/* %partial% */

import { FormKit, useFormKitNodeById } from '@formkit/react'

const formLabelStyle = {
  fontSize: '0.875rem',
  color: '#1e293b',
  marginBottom: '1rem',
  padding: '0.5rem',
  borderRadius: '0.375rem',
  backgroundColor: '#f1f5f9',
}

/* %partial% */
const castRangeToNumber = (node) => {
  if (node.props.type !== 'range') return
  node.hook.input((value, next) => next(Number(value)))
}

const CHARACTER_BASE_STATS = {
  Warrior: {
    strength: 9,
    skill: 1,
    dexterity: 5,
  },
  Mage: {
    strength: 5,
    skill: 10,
    dexterity: 8,
  },
  Assassin: {
    strength: 5,
    skill: 4,
    dexterity: 10,
  },
}

function useAttributeUpdater() {
  const classNode = useFormKitNodeById('class')
  const attributesNode = useFormKitNodeById('attributes')

  useEffect(() => {
    if (!classNode || !attributesNode) return

    const receipt = classNode.on('commit', ({ payload }) => {
      if (CHARACTER_BASE_STATS[payload]) {
        attributesNode.input(CHARACTER_BASE_STATS[payload])
      }
    })

    return () => {
      classNode.off(receipt)
    }
  }, [attributesNode, classNode])
}

const createCharacter = async (fields) => {
  await new Promise((resolve) => setTimeout(resolve, 1000))
  alert(JSON.stringify(fields))
}
/* %partial% */

function CharacterAttributesUpdateExample() {
  useAttributeUpdater()

  return (
    <>
      {/* %partial% */}
      <div>
        <h4 style={formLabelStyle}>Updating values based on the class input</h4>
      </div>
      <h1>New Character</h1>

      <FormKit
        type="form"
        onSubmit={createCharacter}
        plugins={[castRangeToNumber]}
        submitLabel="Create Character"
      >
        {({ value }) => (
          <>
            <FormKit
              type="text"
              name="name"
              id="name"
              validation="required|not:Admin"
              label="Name"
              help="Your full name"
              placeholder="Please add your name"
            />

            <FormKit
              type="select"
              label="Class"
              name="class"
              id="class"
              placeholder="Select a class"
              options={['Warrior', 'Mage', 'Assassin']}
            />

            <FormKit type="group" name="attributes" id="attributes">
              <FormKit
                type="range"
                name="skill"
                id="skill"
                label="Skill"
                defaultValue={5}
                min={1}
                max={10}
                step={1}
                help="How much skill points to start with"
              />

              <FormKit
                type="range"
                name="strength"
                id="strength"
                label="Strength"
                defaultValue={5}
                min={1}
                max={10}
                step={1}
                help="How much strength points to start with"
              />

              <FormKit
                type="range"
                name="dexterity"
                id="dexterity"
                label="Dexterity"
                defaultValue={5}
                min={1}
                max={10}
                step={1}
                help="How many dexterity points should this character have?"
              />
            </FormKit>
            <pre>{JSON.stringify(value, null, 2)}</pre>
          </>
        )}
      </FormKit>

      <p>
        Change the character's class to see the changes in attribute values.
      </p>
      {/* %partial% */}
    </>
  )
}

export default function App() {
  return <CharacterAttributesUpdateExample />
}
