// _examples/node-assignment/node-assignment.vue
<script setup>
import { getNode } from '@formkit/core'

function addValidation() {
  const node = getNode('ssn')
  node.props.validation = 'required|matches:/\\d{3}-\\d{2}-\\d{4}/'
}
</script>

<template>
  <FormKit
    id="ssn"
    label="Social security number"
    type="text"
    help="Initially this input has no validation"
    placeholder="XXX-XX-XXXX"
    validation-visibility="live"
  />

  <FormKit type="button" @click="addValidation">Add validation</FormKit>
</template>

// _examples/node-assignment/node-assignment.react.jsx
import { FormKit, useFormKitNodeById } from '@formkit/react'

function NodeAssignmentExample() {
  const node = useFormKitNodeById('ssn')

  // %partial%
  function addValidation() {
    if (node) {
      node.props.validation = 'required|matches:/\\d{3}-\\d{2}-\\d{4}/'
    }
  }
  // %partial%

  return (
    <>
      <FormKit
        id="ssn"
        label="Social security number"
        type="text"
        help="Initially this input has no validation"
        placeholder="XXX-XX-XXXX"
        validationVisibility="live"
      />

      <FormKit type="button" onClick={addValidation}>
        Add validation
      </FormKit>
    </>
  )
}
// %partial%

export default function App() {
  return <NodeAssignmentExample />
}
