// _examples/unit/unit.vue
<script setup>
const initialValues = {
  distance: 100,
  temperature: 100,
  time: 100,
  volume: 100,
  'digital-unit': 100,
}
</script>

<template>
  <FormKit
    v-slot="{ value }"
    type="form"
    :actions="false"
    :value="initialValues"
  >
    <!-- %partial%::html:: -->
    <FormKit
      type="unit"
      unit="kilometer"
      name="distance"
      label="Distance in meters"
    />
    <FormKit
      type="unit"
      unit="celsius"
      name="temperature"
      label="Temperature in Celsius"
    />
    <FormKit
      type="unit"
      unit="nanosecond"
      name="time"
      label="Time in nanoseconds"
    />
    <FormKit
      type="unit"
      unit="fluid-ounce"
      name="volume"
      label="Volume in fluid ounces"
    />
    <FormKit
      type="unit"
      unit="megabyte"
      name="digital-unit"
      label="Digital unit in megabytes"
    />
    <pre wrap>{{ value }}</pre>
    <!-- %partial%::html:: -->
  </FormKit>
</template>

// _examples/unit/unit.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: {
    ...genesisIcons,
  },
})

export default function App() {
  return (
    <FormKit type="form" actions={false}>
      {({ value }) => (
        <>
          {/* %partial% */}
          <FormKit
            type="unit"
            unit="kilometer"
            name="distance"
            label="Distance in meters"
            defaultValue={100}
          />
          <FormKit
            type="unit"
            unit="celsius"
            name="temperature"
            label="Temperature in Celsius"
            defaultValue={100}
          />
          <FormKit
            type="unit"
            unit="nanosecond"
            name="time"
            label="Time in nanoseconds"
            defaultValue={100}
          />
          <FormKit
            type="unit"
            unit="fluid-ounce"
            name="volume"
            label="Volume in fluid ounces"
            defaultValue={100}
          />
          <FormKit
            type="unit"
            unit="megabyte"
            name="digital-unit"
            label="Digital unit in megabytes"
            defaultValue={100}
          />
          <pre>{JSON.stringify(value, null, 2)}</pre>
          {/* %partial% */}
        </>
      )}
    </FormKit>
  )
}
