// examples/otp-first-value/Register.vue
<template>
  <FormKit type="form" v-model="values">
    <FormKit
      :type="otp"
      label="One-time password"
      name="two_factor_code"
      help="We’ve sent a code to your phone."
      validation="required"
      validation-visibility="live"
    />
  </FormKit>

  <!-- This is just to help us visualize the data in our form: -->
  <pre wrap>{{ values }}</pre>
</template>

<script setup>
import { ref } from 'vue'
import { createInput } from '@formkit/vue'
import OneTimePassword from 'OneTimePassword.vue'

const values = ref({})
const otp = createInput(OneTimePassword)
</script>

// _examples/otp-first-value/register.react.jsx
import { useState } from 'react'

/* %partial% */
import { FormKit, createInput } from '@formkit/react'
import OneTimePassword from './one-time-password.react.jsx'

const otp = createInput(OneTimePassword)

function FirstValueExample() {
  const [values, setValues] = useState({})

  return (
    <>
      <FormKit
        type="form"
        modelValue={values}
        onUpdateModelValue={(value) => setValues(value ?? {})}
      >
        <FormKit
          type={otp}
          label="One-time password"
          name="two_factor_code"
          help="We’ve sent a code to your phone."
          validation="required"
          validationVisibility="live"
        />
      </FormKit>

      <pre>{JSON.stringify(values, null, 2)}</pre>
    </>
  )
}
/* %partial% */

export default function App() {
  return <FirstValueExample />
}
