// _examples/dropdown/dropdown-option-loader.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

// %partial%
async function loadCurrentlyPopularMovies({ page, hasNextPage }) {
  const res = await fetch(
    `https://api.themoviedb.org/3/movie/popular?api_key=f48bcc9ed9cbce41f6c28ea181b67e14&language=en-US&page=${page}`
  )
  if (res.ok) {
    const data = await res.json()
    if (page !== data.total_pages) hasNextPage()
    return data.results.map((item) => ({ label: item.title, value: item.id }))
  }
  return []
}

async function loadMovie(id, cachedOption) {
  if (cachedOption) return cachedOption
  const res = await fetch(
    `https://api.themoviedb.org/3/movie/${id}?api_key=f48bcc9ed9cbce41f6c28ea181b67e14&language=en-US`
  )
  if (res.ok) {
    const data = await res.json()
    return {
      label: data.title,
      value: data.id,
    }
  }
  return { label: 'Error loading' }
}

function DropdownExample() {
  return (
    <FormKit
      type="dropdown"
      name="currentlyPopularMovie"
      label="Choose some movies you would like to see"
      placeholder="Avatar, Star Wars..."
      options={loadCurrentlyPopularMovies}
      optionLoader={loadMovie}
      multiple
      popover
      defaultValue={[597, 598]}
    />
  )
}
// %partial%

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return <DropdownExample />
}

// examples/dropdown/dropdown-option-loader.vue
<script setup>
import { ref } from 'vue'
const movieReview = ref(null)
async function loadCurrentlyPopularMovies({ page, hasNextPage }) {
  const res = await fetch(`https://api.themoviedb.org/3/movie/popular?api_key=f48bcc9ed9cbce41f6c28ea181b67e14&language=en-US&page=${page}`)
  if (res.ok) {
    const data = await res.json()
    if (page !== data.total_pages) hasNextPage()
    return data.results.map((item) => ({ label: item.title, value: item.id }))
  }
  return []
}

// The function assigned to the `option-loader` prop
// will be called with the value of the option as
// its first argument, and the option object as its
// second.
async function loadMovie(id, option) {
  const res = await fetch(`https://api.themoviedb.org/3/movie/${id}/reviews?api_key=f48bcc9ed9cbce41f6c28ea181b67e14&language=en-US`)
  if (res.ok) {
    const data = await res.json()
    // Here we are setting the value of our
    // `movieReview` ref to the first review
    movieReview.value = data.results[0].content + ' ' + data.results[0].author
    return { label: option.label, value: id }
  }
  return { label: 'Error loading' }
}
</script>

<template>
  <FormKit
    type="form"
    :actions="false"
  >
    <FormKit
      type="dropdown"
      name="currentlyPopularMovie"
      label="Choose a currently popular movie"
      placeholder="Example placeholder"
      :options="loadCurrentlyPopularMovies"
      :option-loader="loadMovie"
    />
    <pre class="movie-review">{{ movieReview }}</pre>
  </FormKit>
</template>

<style>
.movie-review {
  white-space: pre-wrap;
}
</style>
