// _examples/schema-expressions/schema-expressions.vue
<script setup>
import { reactive } from 'vue'

const schema = [
  {
    $el: 'div',
    // You can use expressions to concatenate strings
    children: '$: "Qty: " + $count + " x " + $format($price)'
  },
  {
    $el: 'div',
    children: [
      'Shipping: ',
      '$format($ship)'
    ]
  },
  {
    $el: 'div',
    children: [
      'Total: ',
      // No label needed since $format starts with $
      '$format(($count * $price) + $ship)'
    ]
  }
]
const data = reactive({
  count: 1,
  price: 15.29,
  ship: 9.99,
  format: Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format
})
</script>

<template>
  <FormKitSchema
    :schema="schema"
    :data="data"
  />
  <FormKit type="button" @click="data.count++">Add to cart</FormKit>
</template>

// _examples/schema-expressions/schema-expressions.react.jsx
// %partial%
import { useMemo, useState } from 'react'
import { FormKit, FormKitSchema } from '@formkit/react'

const schema = [
  {
    $el: 'div',
    children: '$: "Qty: " + $count + " x " + $format($price)',
  },
  {
    $el: 'div',
    children: ['Shipping: ', '$format($ship)'],
  },
  {
    $el: 'div',
    children: ['Total: ', '$format(($count * $price) + $ship)'],
  },
]

function Example() {
  const [count, setCount] = useState(1)
  const format = useMemo(
    () =>
      Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format,
    []
  )
  const data = {
    count,
    price: 15.29,
    ship: 9.99,
    format,
  }

  return (
    <>
      <FormKitSchema schema={schema} data={data} />
      <FormKit
        type="button"
        onClick={() => setCount((current) => current + 1)}
        outerClass="mt-6"
      >
        Add to cart
      </FormKit>
    </>
  )
}
// %partial%

export default function App() {
  return <Example />
}
