// _examples/locale-change-2/change-locale-2.react.jsx
// %partial%
import { FormKit } from '@formkit/react'
import { changeLocale } from '@formkit/i18n'
export { default as formkitConfig } from './formkit.config.react.jsx'

export default function App() {
  return (
    <>
      <button
        className="border-2 px-2 py-1 mb-4"
        onClick={() => changeLocale('zh')}
      >
        Set to Chinese
      </button>
      <FormKit
        type="text"
        validation="required|length:10"
        name="username"
        validationVisibility="live"
      />
    </>
  )
}
// %partial%

// .examples/locale-change-2/change-locale-2.vue
<script setup>
import { changeLocale } from '@formkit/vue'
</script>

<template>
  <button class="border-2 px-2 py-1 mb-4" @click="changeLocale('zh')">
    Set to Chinese
  </button>
  <FormKit
    type="text"
    validation="required|length:10"
    name="username"
    validation-visibility="live"
  />
</template>
