// examples/mask/reverse.vue
<template>
<!-- %partial%::html:: -->
<FormKit type="form" :actions="false" #default="{ value }">
  <FormKit
    type="mask"
    reverse
    prefix="€"
    name="bid"
    mask="{#,##|repeat}#.##"
    label="Bid"
    show-mask="false"
    allow-incomplete="true"
    help="Enter your bid for the art piece."
  />
  <pre wrap>{{ value }}</pre>  
</FormKit>
<!-- %partial%::html:: -->
</template>

// _examples/mask/reverse.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit type="form" actions={false}>
        {({ value }) => (
          <>
            <FormKit
              type="mask"
              reverse
              prefix="\u20ac"
              name="bid"
              mask="{#,##|repeat}#.##"
              label="Bid"
              showMask={false}
              allowIncomplete
              help="Enter your bid for the art piece."
            />
            <pre>{JSON.stringify(value, null, 2)}</pre>
          </>
        )}
      </FormKit>
      {/* %partial% */}
    </>
  )
}
