// examples/mask/tokens-prop.vue
<template>
  <!-- %partial%::html:: -->
  <FormKit
    type="mask"
    name="promo_code"
    mask="zzz-#### ####"
    :tokens="{
      z: {
        type: 'char',
        token: 'z',
        pattern: /[A-Za-z0-9]/,
        placeholder: '_',
        selectDirection: 'left',
      },
    }"
    value="a6d-7789 4398"
    label="Promo code"
    help="Enter a promo code in the format: fkt-1234 5678"
  />
  <!-- %partial%::html:: -->
</template>

// _examples/mask/tokens-prop.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit
        type="mask"
        name="promo_code"
        mask="zzz-#### ####"
        tokens={{
          z: {
            type: 'char',
            token: 'z',
            pattern: /[A-Za-z0-9]/,
            placeholder: '_',
            selectDirection: 'left',
          },
        }}
        defaultValue="a6d-7789 4398"
        label="Promo code"
        help="Enter a promo code in the format: fkt-1234 5678"
      />
      {/* %partial% */}
    </>
  )
}
