// examples/mask/unmask-value.vue
<template>
  <!-- %partial%::html:: -->
  <FormKit type="form" #default="{ value }">
    <FormKit
      type="mask"
      name="phone"
      mask="(###) ###-####"
      label="Phone number"
      help="Enter a full phone number. See the value has no string literals."
      unmask-value="true"
    />
    <pre wrap>{{ value }}</pre>
  </FormKit>
  <!-- %partial%::html:: -->
</template>


<style>
pre[wrap] { margin-bottom: 20px !important; }
</style>

// _examples/mask/unmask-value.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit type="form">
        {({ value }) => (
          <>
            <FormKit
              type="mask"
              name="phone"
              mask="(###) ###-####"
              label="Phone number"
              help="Enter a full phone number. See the value has no string literals."
              unmaskValue
            />
            <pre>{JSON.stringify(value, null, 2)}</pre>
          </>
        )}
      </FormKit>
      {/* %partial% */}
    </>
  )
}
