// _examples/schema-components/schema-components.react.jsx
// %partial%
import { FormKitSchema } from '@formkit/react'

function CustomComponent({ name }) {
  return <>Hello {name}</>
}

const library = {
  MyComponent: CustomComponent,
}

const schema = [
  {
    $cmp: 'MyComponent',
    props: {
      name: 'Jane',
    },
  },
]

function Example() {
  return <FormKitSchema schema={schema} library={library} />
}
// %partial%

export default function App() {
  return <Example />
}

// _examples/schema-components/schema-components.vue
<script setup>
import { markRaw } from 'vue'

// A custom component, typically imported from elsewhere
const CustomComponent = {
  props: ['name'],
  template: `Hello {{ name }}`,
}

// Assign the custom component a library
const library = markRaw({
  MyComponent: CustomComponent,
})

// Reference the key of the desired component from
// the library.
const schema = [
  {
    $cmp: 'MyComponent',
    props: {
      name: 'Jane',
    },
  },
]
</script>

<template>
  <FormKitSchema 
    :schema="schema" 
    :library="library" 
  />
</template>
