// _examples/guides/tailwind-theme/inline-usage/example.react.jsx
export { default as formkitConfig } from '../../../_no-tailwind/formkit.config.react.jsx'
/* %partial% */
import { FormKit } from '@formkit/react'

function TailwindThemeInlineUsageExample() {
  return (
    <>
      {/* using section-key class props */}
      <FormKit
        type="text"
        label="Section-key class props"
        help="Look, Ma! Tailwind styles"
        outerClass="mb-5"
        labelClass="mb-1 block text-sm font-bold"
        innerClass="mb-1 max-w-md overflow-hidden rounded-lg border border-gray-400 focus-within:border-blue-500"
        inputClass="h-10 w-full border-none px-3 text-base text-gray-700 placeholder-gray-400"
        helpClass="text-xs text-gray-500"
      />
      {/* using the classes prop */}
      <FormKit
        type="text"
        label="Classes prop"
        help="Look, Ma! Tailwind styles"
        classes={{
          outer: 'mb-5',
          label: 'mb-1 block text-sm font-bold',
          inner:
            'mb-1 max-w-md overflow-hidden rounded-lg border border-gray-400 focus-within:border-blue-500',
          input:
            'h-10 w-full border-none px-3 text-base text-gray-700 placeholder-gray-400',
          help: 'text-xs text-gray-500',
        }}
      />
    </>
  )
}
/* %partial% */

export default function App() {
  return <TailwindThemeInlineUsageExample />
}

// _examples/guides/root-classes-tailwind-old/inline-usage/example.vue
<template>
  <!-- %partial% -->
  <!-- using section-key class props -->
  <FormKit
    type="text"
    label="Section-key class props"
    help="Look, Ma! Tailwind styles"
    outer-class="mb-5"
    label-class="block mb-1 font-bold text-sm"
    inner-class="max-w-md border border-gray-400 rounded-lg mb-1 overflow-hidden focus-within:border-blue-500 dark:border-gray-700"
    input-class="w-full bg-transparent h-10 px-3 border-none text-base text-gray-700 placeholder-gray-400 dark:text-gray-300"
    help-class="text-xs text-gray-500"
  />
  <!-- using the classes prop -->
  <FormKit
    type="text"
    label="Classes prop"
    help="Look, Ma! Tailwind styles"
    :classes="{
      outer: 'mb-5',
      label: 'block mb-1 font-bold text-sm',
      inner: 'max-w-md border border-gray-400 rounded-lg mb-1 overflow-hidden focus-within:border-blue-500 dark:border-gray-700',
      input: 'w-full bg-transparent h-10 px-3 border-none text-base text-gray-700 placeholder-gray-400 dark:text-gray-300',
      help: 'text-xs text-gray-500'
    }"
  />
  <!-- %partial% -->
</template>
