// _examples/radio-strings/radio-strings.react.jsx
import { useState } from 'react'
import { FormKit } from '@formkit/react'

export default function App() {
  const [value, setValue] = useState()

  return (
    <>
      {/* %partial% */}
      <FormKit
        modelValue={value}
        onUpdateModelValue={setValue}
        type="radio"
        label="Preferred transportation"
        options={[
          'E-Bike',
          'E-Scooter',
          'Electric car',
          'Walking',
          'Space tube',
        ]}
        help="How do you like to get around?"
      />
      <pre>{value}</pre>
      {/* %partial% */}
    </>
  )
}

// examples/radio-strings/radio-strings.vue
<template>
  <!-- %partial%::html:: -->
  <FormKit
    v-model="value"
    type="radio"
    label="Preferred transportation"
    :options="['E-Bike', 'E-Scooter', 'Electric car', 'Walking', 'Space tube']"
    help="How do you like to get around?"
  />
  <pre wrap>{{ value }}</pre>
  <!-- %partial%::html:: -->
</template>

<script setup>
import { ref } from 'vue'
const value = ref(undefined)
</script>
