// examples/dropdown/dropdown-single-request.vue
<script setup>
import { ref } from 'vue'
const value = ref(null)

async function loadHorrorMovies() {
  const res = await fetch(`https://api.themoviedb.org/4/list/8219282?page=1&api_key=f48bcc9ed9cbce41f6c28ea181b67e14`)
  if (res.ok) {
    const data = await res.json()
    // Iterating over results to set the required
    // `label` and `value` keys.
    return data.results.map((result) => {
      return {
        label: result.title,
        value: result.id
      }
    })
  }
  // If the request fails, we return an empty array.
  return []
}
</script>

<template>
  <!--Setting the `options` prop to async function `loadMovies`-->
  <FormKit
    v-model="value"
    type="dropdown"
    label="Select a horror movie"
    placeholder="Example placeholder"
    :options="loadHorrorMovies"
  />
  <pre wrap>
    Value {{ value }}
  </pre>
</template>

<style>
.formkit-option {
  display: flex;
  align-items: center;
}

.formkit-option img {
  width: 20%;
  margin-right: 20px;
}

.option-overview {
  font-size: 12px;
}
</style>

// _examples/dropdown/dropdown-single-request.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

// %partial%
async function loadHorrorMovies() {
  await new Promise((resolve) => setTimeout(resolve, 500))
  const res = await fetch(
    'https://api.themoviedb.org/4/list/8219282?page=1&api_key=f48bcc9ed9cbce41f6c28ea181b67e14'
  )
  if (res.ok) {
    const data = await res.json()
    return data.results.map((result) => {
      return {
        label: result.title,
        value: result.id,
      }
    })
  }
  return []
}

function DropdownExample() {
  return (
    <FormKit
      name="horrorMovie"
      type="dropdown"
      label="Select a horror movie"
      placeholder="Example placeholder"
      popover
      options={loadHorrorMovies}
    />
  )
}
// %partial%

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return <DropdownExample />
}
