// _examples/autocomplete-pro/autocomplete-close-on-select.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'
import countries from '../_data/countries.js'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit
        type="autocomplete"
        name="autocomplete"
        label="Search for a country"
        options={countries}
        multiple
        closeOnSelect={false}
        placeholder="Example: United States"
        popover
      />
      {/* %partial% */}
    </>
  )
}

// .examples/autocomplete-pro/autocomplete-close-on-select.vue
<script setup>
import countries from './countries.js'
</script>

<template>
  <!-- %partial% -->
  <FormKit
    type="autocomplete"
    name="autocomplete"
    label="Search for a country"
    :options="countries"
    multiple
    :close-on-select="false"
    placeholder="Example: United States"
  />
  <!-- %partial% -->
</template>
