// _examples/autocomplete-pro/autocomplete-single-request.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

// %partial%
// Search movie receives FormKit's context object
// which we are destructuring to get the search value.
async function searchMovies({ search }) {
  if (!search) return []
  const response = await fetch(
    `https://api.themoviedb.org/3/search/movie?query=${
      search || ''
    }&api_key=f48bcc9ed9cbce41f6c28ea181b67e14&language=en-US&page=1&include_adult=false`
  )
  if (response.ok) {
    const data = await response.json()
    // Iterating over results to set the required
    // `label` and `value` keys.
    return data.results.map((result) => ({
      label: result.title,
      value: result.id,
    }))
  }
  // If the request fails, we return an empty array.
  return []
}
// %partial%

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit
        name="movie"
        type="autocomplete"
        label="Search for your favorite movie"
        placeholder="Example: Shawshank Redemption"
        popover
        options={searchMovies}
      />
      {/* %partial% */}
    </>
  )
}

// .examples/autocomplete-pro/autocomplete-single-request.vue
<script setup>
// Search movie receives FormKit's context object
// which we are destructuring to get the search value.
async function searchMovies({ search }) {
  if (!search) return [];
  const res = await fetch(`https://api.themoviedb.org/3/search/movie?query=${search || ''}&api_key=f48bcc9ed9cbce41f6c28ea181b67e14&language=en-US&page=1&include_adult=false`)
  if (res.ok) {
    const data = await res.json()
    // Iterating over results to set the required
    // `label` and `value` keys.
    return data.results.map((result) => {
      return {
        label: result.title,
        value: result.id
      }
    })
  }
  // If the request fails, we return an empty array.
  return []
}
</script>

<template>
  <!--Setting the `options` prop to async function `loadHorrorMovies`-->
  <FormKit
    name="movie"
    type="autocomplete"
    label="Search for your favorite movie"
    placeholder="Example: Shawshank Redemption"
    popover
    :options="searchMovies"
  />
</template>

<style>
.formkit-option {
  display: flex;
  align-items: center;
}

.formkit-option img {
  width: 20%;
  margin-right: 20px;
}

.option-overview {
  font-size: 12px;
}
</style>
