// _examples/dropdown/dropdown-max.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

// %partial%
import countries from '../_data/countries.js'

function DropdownExample() {
  return (
    <FormKit type="form" actions={false}>
      {({ value }) => (
        <>
          <FormKit
            type="dropdown"
            name="countries"
            label="Choose your favorite countries"
            placeholder="Afghanistan, Albania..."
            options={countries}
            multiple
            popover
            max="3"
            defaultValue={['AF', 'AL']}
          />
          <pre>{JSON.stringify(value, null, 2)}</pre>
        </>
      )}
    </FormKit>
  )
}
// %partial%

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return <DropdownExample />
}

// .examples/dropdown/dropdown-max.vue
<script setup>
import countries from './countries.js'
</script>

<template>
  <FormKit type="form" #default="{ value }" :actions="false">
    <FormKit
      type="dropdown"
      name="countries"
      label="Choose your favorite countries"
      placeholder="Afghanistan, Albania..."
      :options="countries"
      multiple
      max="3"
      :value="['AF', 'AL']"
    />
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>

<style></style>
