// _examples/rule-confirm/rule-confirm.react.jsx
import { FormKit } from '@formkit/react'

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit type="group">
        <FormKit
          type="password"
          name="password"
          label="Password"
          validation="required"
          validationVisibility="live"
        />
        <FormKit
          type="password"
          name="password_confirm"
          label="Confirm password"
          validation="required|confirm"
          validationVisibility="live"
          validationLabel="Confirmation"
        />
      </FormKit>
      {/* %partial% */}
    </>
  )
}

// examples/rule-confirm/rule-confirm.vue
<template>
<!-- %partial%::html:: -->
<FormKit type="group">
  <FormKit
    type="password"
    name="password"
    label="Password"
    validation="required"
    validation-behavior="live"
  />
  <FormKit
    type="password"
    name="password_confirm"
    label="Confirm password"
    validation="required|confirm"
    validation-behavior="live"
    validation-label="Confirmation"
  />
</FormKit>
<!-- %partial%::html:: -->
</template>
