// _examples/datepicker/datepicker-time.vue
<template>
  <FormKit type="form" #default="{ value }" :actions="false">
    <FormKit
      type="datepicker"
      name="reservation"
      label="Dinner reservation"
      help="Select a time for your dinner reservation."
      placeholder="Select a time"
      format="MMM D \at hh:mm A"
      :sequence="['day', 'time']"
      picker-only
      popover
    />
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>

// _examples/datepicker/datepicker-time.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit type="form" actions={false}>
        {({ value }) => (
          <>
            <FormKit
              type="datepicker"
              name="reservation"
              label="Dinner reservation"
              help="Select a time for your dinner reservation."
              placeholder="Select a time"
              format="MMM D \\at hh:mm A"
              sequence={['day', 'time']}
              pickerOnly
              popover
            />
            <pre>{JSON.stringify(value, null, 2)}</pre>
          </>
        )}
      </FormKit>
      {/* %partial% */}
    </>
  )
}
