// _examples/datepicker/datepicker-styles.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit type="form" actions={false}>
        {({ value }) => (
          <>
            <FormKit
              type="datepicker"
              name="reservation_time"
              label="Reservation time"
              help="Select a date and time to reserve your scuba equipment."
              format={{ date: 'short', time: 'short' }}
              sequence={['day', 'time']}
              overlay
              popover
            />
            <pre>{JSON.stringify(value, null, 2)}</pre>
          </>
        )}
      </FormKit>
      {/* %partial% */}
    </>
  )
}

// _examples/datepicker/datepicker-styles.vue
<template>
  <FormKit type="form" #default="{ value }" :actions="false">
    <FormKit
      type="datepicker"
      name="reservation_time"
      label="Reservation time"
      help="Select a date and time to reserve your scuba equipment."
      :format="{ date: 'short', time: 'short' }"
      :sequence="['day', 'time']"
      overlay
      popover
    />
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>
