// _examples/datepicker/datepicker-dual-mode.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit type="form" actions={false}>
        {({ value }) => (
          <>
            <FormKit
              type="datepicker"
              name="meeting_date"
              label="Meeting date"
              format={{ date: 'short' }}
              popover
              help="What date should we schedule the meeting?"
            />
            <pre>{JSON.stringify(value, null, 2)}</pre>
          </>
        )}
      </FormKit>
      {/* %partial% */}
    </>
  )
}

// _examples/datepicker/datepicker-dual-mode.vue
<template>
  <FormKit type="form" #default="{ value }" :actions="false">
    <FormKit
      type="datepicker"
      name="meeting_date"
      label="Meeting date"
      :format="{ date: 'short' }"
      popover
      help="What date should we schedule the meeting?"
    />
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>
