// .examples/datepicker/datepicker-clearable.vue
<template>
  <FormKit type="form" #default="{ value }" :actions="false">
    <FormKit
      type="datepicker"
      name="vacation_date"
      label="Time off request"
      help="Please select the date you would like to start your vacation."
      placeholder="Select a date"
      :value="new Date()"
      popover
      clearable
    />
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>

// _examples/datepicker/datepicker-clearable.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit type="form" actions={false}>
        {({ value }) => (
          <>
            <FormKit
              type="datepicker"
              name="vacation_date"
              label="Time off request"
              help="Please select the date you would like to start your vacation."
              placeholder="Select a date"
              defaultValue={new Date()}
              popover
              clearable
            />
            <pre>{JSON.stringify(value, null, 2)}</pre>
          </>
        )}
      </FormKit>
      {/* %partial% */}
    </>
  )
}
