// _examples/datepicker/datepicker-indeterminate.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit type="form" actions={false}>
        {({ value }) => (
          <>
            <FormKit
              type="datepicker"
              name="alarm"
              label="Set an alarm"
              help="When should your alarm ring?"
              format={{ time: 'short' }}
              valueFormat="HH:mm"
              sequence={['time']}
              sectionsSchema={{
                panelHeader: {
                  $el: null,
                  children: [],
                },
              }}
              overlay
              popover
            />
            <pre>{JSON.stringify(value, null, 2)}</pre>
          </>
        )}
      </FormKit>
      {/* %partial% */}
    </>
  )
}

// _examples/datepicker/datepicker-indeterminate.vue
<template>
  <FormKit type="form" #default="{ value }" :actions="false">
    <FormKit
      type="datepicker"
      name="alarm"
      label="Set an alarm"
      help="When should your alarm ring?"
      :format="{ time: 'short' }"
      value-format="HH:mm"
      :sequence="['time']"
      :sections-schema="{
        // disable the header since we don’t need it.
        panelHeader: {
          $el: null,
          children: [],
        },
      }"
      overlay
      popover
    />
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>
