// .examples/datepicker/datepicker-sequence.vue
<template>
  <FormKit type="form" #default="{ value }" :actions="false">
    <FormKit
      type="datepicker"
      name="birthday"
      label="Birthday"
      help="Select your birthday"
      placeholder="Select a birthday"
      format="full"
      :sequence="['year', 'month', 'day']"
      picker-only
    />
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>

// _examples/datepicker/datepicker-sequence.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit type="form" actions={false}>
        {({ value }) => (
          <>
            <FormKit
              type="datepicker"
              name="birthday"
              label="Birthday"
              help="Select your birthday"
              placeholder="Select a birthday"
              format="full"
              sequence={['year', 'month', 'day']}
              pickerOnly
              popover
            />
            <pre>{JSON.stringify(value, null, 2)}</pre>
          </>
        )}
      </FormKit>
      {/* %partial% */}
    </>
  )
}
