// examples/schema-bind/schema-bind.vue
<script setup>
import { reactive } from 'vue'

const schema = [
  {
    $el: 'h1',
    // 👀 Look below for the data object with this
    bind: '$someAttributes',
    children: 'Click me!',
  },
]

const data = reactive({
  someAttributes: {
    class: 'red',
    onClick: () => {
      if (data.someAttributes.class === 'red') {
        data.someAttributes.class = 'blue'
      } else {
        data.someAttributes.class = 'red'
      }
    },
    'data-fruit': 'I like fruit',
  },
})
</script>

<template>
  <FormKitSchema :schema="schema" :data="data" />
</template>

<style>
.red {
  color: red;
}
.blue {
  color: blue;
}
</style>

// _examples/schema-bind/schema-bind.react.jsx
// %partial%
import { useState } from 'react'
import { FormKitSchema } from '@formkit/react'

const schema = [
  {
    $el: 'h1',
    bind: '$someAttributes',
    children: 'Click me!',
  },
]

function Example() {
  const [colorClass, setColorClass] = useState('!text-red-500')
  const data = {
    someAttributes: {
      class: colorClass,
      onClick: () => {
        setColorClass((current) =>
          current === '!text-red-500' ? '!text-blue-500' : '!text-red-500'
        )
      },
      'data-fruit': 'I like fruit',
    },
  }

  return <FormKitSchema schema={schema} data={data} />
}
// %partial%

export default function App() {
  return <Example />
}
