// _examples/taglist/taglist-base.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

// %partial%
import carBrands from '../_data/car-brands.js'

function TaglistExample() {
  return (
    <FormKit type="form" actions={false}>
      {({ value }) => (
        <>
          <FormKit
            type="taglist"
            name="car_brands"
            label="Search for your favorite car brands"
            popover
            options={carBrands}
            defaultValue={['honda', 'toyota']}
          />
          <pre>{JSON.stringify(value, null, 2)}</pre>
        </>
      )}
    </FormKit>
  )
}
// %partial%

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return <TaglistExample />
}

// .examples/taglist/taglist-base.vue
<script setup>
import carBrands from './car-brands.js'
</script>

<template>
  <FormKit type="form" #default="{ value }" :actions="false">
    <FormKit
      type="taglist"
      name="car_brands"
      label="Search for your favorite car brands"
      popover
      :options="carBrands"
      :value="['honda', 'toyota']"
    />
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>
