// _examples/taglist/taglist-filter.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

// %partial%
import countries from '../_data/countries.js'

const filterCountries = (option, search) =>
  option.label.toLowerCase().startsWith(search.toLowerCase())

function TaglistExample() {
  return (
    <FormKit type="form" actions={false}>
      {({ value }) => (
        <>
          <FormKit
            type="taglist"
            name="taglist"
            label="Search for a country"
            popover
            options={countries}
            defaultValue={['AX', 'AL']}
            filter={filterCountries}
          />
          <pre>{JSON.stringify(value, null, 2)}</pre>
        </>
      )}
    </FormKit>
  )
}
// %partial%

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return <TaglistExample />
}

// .examples/taglist/taglist-filter.vue
<script setup>
import countries from './countries.js'
</script>

<template>
  <FormKit
    type="form"
    #default="{ value }"
    :actions="false"
  >
    <FormKit
      type="taglist"
      name="taglist"
      label="Search for a country"
      :options="countries"
      :value="['AX', 'AL']"
      :filter="(option, search) =>
        option.label.toLowerCase().startsWith(search.toLowerCase())"
    />
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>
