// _examples/taglist/taglist-slots.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, FormKitIcon, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

// %partial%
import carBrands from '../_data/car-brands.js'

function TaglistExample() {
  return (
    <FormKit type="form" actions={false}>
      {({ value }) => (
        <>
          <FormKit
            type="taglist"
            name="taglist"
            label="Search and select a car brand"
            placeholder="Example: Toyota"
            options={carBrands}
            popover
            selectionAppearance="option"
            defaultValue={['audi', 'bmw']}
            multiple
            slots={{
              tag: ({ handlers, option, classes }) => (
                <div className={classes.tag}>
                  <img src={option.logo} className="w-5 mr-2 bg-white" />
                  <span className={classes.tagLabel}>{option.label}</span>
                  <button
                    type="button"
                    tabIndex={-1}
                    className="formkit-remove-selection"
                    onClick={(event) => {
                      event.preventDefault()
                      handlers.removeSelection(option)()
                    }}
                  >
                    <span className="formkit-close-icon formkit-icon">
                      <FormKitIcon icon="close" />
                    </span>
                  </button>
                </div>
              ),
            }}
          />
          <pre>{JSON.stringify(value, null, 2)}</pre>
        </>
      )}
    </FormKit>
  )
}
// %partial%

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return <TaglistExample />
}

// .examples/taglist/taglist-slots.vue
<script setup>
import carBrands from './car-brands.js'
</script>

<template>
  <FormKit type="form" #default="{ value }" :actions="false">
    <FormKit
      type="taglist"
      name="taglist"
      label="Search and select a car brand"
      placeholder="Example: Toyota"
      :options="carBrands"
      selection-appearance="option"
      :value="['audi', 'bmw']"
      multiple
    >
      <!--TAG SLOT-->
      <template #tag="{ handlers, option, classes }">
        <div :class="classes.tag">
          <img :src="option.logo" class="w-5 mr-2 bg-white" />
          <span :class="classes.tagLabel">
            {{ option.label }}
          </span>
          <button
            @click.prevent="handlers.removeSelection(option)()"
            tabindex="-1"
            type="button"
            aria-controls="input_1"
            class="formkit-remove-selection"
          >
            <span class="formkit-close-icon formkit-icon"
              ><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 16">
                <path
                  d="M10,12.5c-.13,0-.26-.05-.35-.15L1.65,4.35c-.2-.2-.2-.51,0-.71,.2-.2,.51-.2,.71,0L10.35,11.65c.2,.2,.2,.51,0,.71-.1,.1-.23,.15-.35,.15Z"
                  fill="currentColor"
                ></path>
                <path
                  d="M2,12.5c-.13,0-.26-.05-.35-.15-.2-.2-.2-.51,0-.71L9.65,3.65c.2-.2,.51-.2,.71,0,.2,.2,.2,.51,0,.71L2.35,12.35c-.1,.1-.23,.15-.35,.15Z"
                  fill="currentColor"
                ></path></svg
            ></span>
          </button>
        </div>
      </template>
      <!--/TAG SLOT-->
    </FormKit>
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>
