// examples/transfer-list/transfer-list-rehydrating-values.vue
<script setup>
async function searchGuests({ search }) {
  if (!search) {
    return []
  }
  const res = await fetch(`https://api-formkit-docs-examples.formkit.workers.dev/guests?search=${search}`)
  if (res.ok) {
    const data = await res.json()
    if (data.data) {
      return data.data.map((result) => {
        return {
          label: result.name,
          value: result.id,
        }
      })
    }
  }
  return []
}

async function getGuest(id, cachedOption) {
  if (cachedOption) return cachedOption
  const res = await fetch(`https://api-formkit-docs-examples.formkit.workers.dev/guests/${id}`)
  if (res.ok) {
    const data = await res.json()
    console.log('data', data)
    if (data.data) {
      return {
        label: data.data.name,
        value: data.data.id,
      }
    }
  }
}
</script>

<template>
  <FormKit
    type="form"
    #default="{ value }"
    :value="{
      vips: [
        22, 10
      ]
    }"
    :actions="false"
  >
    <FormKit
      name="vips"
      type="transferlist"
      label="Choose VIPs for the party"
      source-label="Guests"
      target-label="VIPs"
      source-empty-message="No guests found"
      target-empty-message="No VIPs selected"
      :options="searchGuests"
      searchable
      placeholder="Search guests"
      :option-loader="getGuest"
    />
    <pre>{{ value }}</pre>
  </FormKit>
</template>

// _examples/transfer-list/transfer-list-rehydrating-values.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'
import { getGuest, searchGuests } from './api.js'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit
        type="form"
        value={{
          vips: [22, 10],
        }}
        actions={false}
      >
        {({ value }) => (
          <>
            <FormKit
              name="vips"
              type="transferlist"
              label="Choose VIPs for the party"
              sourceLabel="Guests"
              targetLabel="VIPs"
              sourceEmptyMessage="No guests found"
              targetEmptyMessage="No VIPs selected"
              options={searchGuests}
              searchable
              placeholder="Search guests"
              optionLoader={getGuest}
            />
            <pre>{JSON.stringify(value, null, 2)}</pre>
          </>
        )}
      </FormKit>
      {/* %partial% */}
    </>
  )
}
