// _examples/transfer-list/transfer-list-ranking.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'
import { nbaTopPlayers } from '../_data/nba-top-players.js'
import { michaelJordan } from './utils.js'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

const rowStyle = {
  display: 'flex',
  alignItems: 'center',
}

const nameStyle = {
  fontSize: '0.8em',
}

const rankStyle = {
  marginRight: '1em',
  color: 'black',
}

const avatarStyle = {
  overflow: 'hidden',
  display: 'block',
  borderRadius: '2em',
  position: 'relative',
  width: '3em',
  height: '3em',
  flex: '0 0 2em',
  marginRight: '0.5em',
}

const imageStyle = {
  width: '100%',
  pointerEvents: 'none',
}

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit
        type="transferlist"
        label="Rank the top 10 NBA players"
        help="Drag and drop to rank your top 10 NBA players."
        options={nbaTopPlayers}
        searchable
        placeholder="Search"
        targetLabel="Your top 10"
        sourceLabel="All-time NBA players"
        validation="michaelJordan"
        validationRules={{ michaelJordan }}
        validationVisibility="dirty"
        validationMessages={{
          michaelJordan: 'Michael Jordan is the undisputed GOAT.',
        }}
        slots={{
          sourceOption: ({ option }) => (
            <div style={rowStyle}>
              <span style={avatarStyle}>
                <img src={option.img_url} alt="" style={imageStyle} />
              </span>
              <span style={nameStyle}>{option.label}</span>
            </div>
          ),
          targetOption: ({ option, index }) => (
            <div style={rowStyle}>
              <span style={rankStyle}>{(index ?? 0) + 1}</span>
              <span style={avatarStyle}>
                <img src={option.img_url} alt="" style={imageStyle} />
              </span>
              <span style={nameStyle}>{option.label}</span>
            </div>
          ),
        }}
      />
      {/* %partial% */}
    </>
  )
}

// _examples/transfer-list/transfer-list-ranking.vue
<script setup>
import { nbaTopPlayers } from 'nba-top-players.js'
import { michaelJordan } from 'utils.js'
</script>

<template>
  <!-- %partial%::html:: -->
  <FormKit
    type="transferlist"
    label="Rank the top 10 NBA players"
    help="Drag and drop to rank your top 10 NBA players."
    :options="nbaTopPlayers"
    searchable
    placeholder="Search"
    target-label="Your top 10"
    source-label="All-time NBA players"
    validation="michaelJordan"
    :validation-rules="{ michaelJordan }"
    validation-visibility="dirty"
    :validation-messages="{
      michaelJordan: 'Michael Jordan is the undisputed GOAT.'
    }"
  >
    <template #sourceOption="{ option }">
      <div class="flex">
        <span class="avatar">
          <img :src="option.img_url" alt="">
        </span>
        <span class="name">
          {{ option.label }}
        </span>
      </div>
    </template>
    <template #targetOption="{ option, index }">
      <div class="flex">
        <span class="rank">
          {{ index + 1 }}
        </span>
        <span class="avatar">
          <img :src="option.img_url" alt="">
        </span>
        <span class="name">
          {{ option.label }}
        </span>
      </div>
    </template>
  </FormKit>
  <!-- %partial%::html:: -->
</template>

<style scoped>
.flex {
  display: flex;
  align-items: center;
}

.name {
  font-size: 0.8em;
}

.rank {
  margin-right: 1em;
  color: black;
}

.avatar {
  overflow: hidden;
  display: block;
  border-radius: 2em;
  position: relative;
  width: 3em;
  height: 3em;
  flex: 0 0 2em;
  margin-right: 0.5em;
}


img {
  width: 100%;
  pointer-events: none;
}
</style>
