// _examples/rating/rating-colors.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: { ...genesisIcons },
})

export default function App() {
  return (
    <FormKit type="form" actions={false}>
      {({ value }) => (
        <>
          {/* %partial% */}
          <FormKit
            type="rating"
            offColor="black"
            onColor="#DA012D"
            ratingIcon="heart"
            label="How much love do you have for FormKit?"
            name="love"
          />
          {/* %partial% */}
          <pre>{JSON.stringify(value, null, 2)}</pre>
        </>
      )}
    </FormKit>
  )
}

// examples/rating/rating-colors.vue
<template>
<!--
  FormKit forms auto-collect values of children inputs.
  Wrap the example in a form so we can display the form values.
-->
<FormKit
  type="form"
  #default="{ value }"
  :actions="false"
>
<!-- %partial%::html:: -->
<FormKit
  type="rating"
  off-color="black"
  on-color="#DA012D"
  rating-icon="heart"
  label="How much love do you have for FormKit?"
  name="love"
/>
<!-- %partial%::html:: -->
  <pre wrap>{{ value }}</pre>
</FormKit>
</template>
