// _examples/rule-max/rule-max-array.vue
<template>
  <!-- %partial%::html:: -->
  <FormKit
    type="checkbox"
    :options="['Pepperoni', 'Sausage', 'Olives', 'Feta', 'Mushrooms']"
    label="Pizza toppings"
    help="Select up to three of your favorite toppings."
    validation="max:3"
    validation-visibility="live"
    :value="['Pepperoni', 'Sausage', 'Olives', 'Feta']"
  />
  <!-- %partial%::html:: -->
</template>

// _examples/rule-max/rule-max-array.react.jsx
import { FormKit } from '@formkit/react'

export default function App() {
  return (
    <>
      {/* %partial% */}
      <FormKit
        type="checkbox"
        options={['Pepperoni', 'Sausage', 'Olives', 'Feta', 'Mushrooms']}
        label="Pizza toppings"
        help="Select up to three of your favorite toppings."
        validation="max:3"
        validationVisibility="live"
        value={['Pepperoni', 'Sausage', 'Olives', 'Feta']}
      />
      {/* %partial% */}
    </>
  )
}
