// _examples/currency/currency-simple-locale.react.jsx
import { genesisIcons } from '@formkit/icons'
import { FormKit, defineFormKitConfig } from '@formkit/react'
import { createProPlugin, inputs as proInputs } from '@formkit/pro'

const pro = createProPlugin('fk-52971f34220', proInputs)
export const formkitConfig = defineFormKitConfig({
  plugins: [pro],
  icons: {
    ...genesisIcons,
  },
})

export default function App() {
  return (
    <FormKit type="form" actions={false}>
      {({ value }) => (
        <>
          {/* %partial% */}
          <FormKit
            type="currency"
            currency="USD"
            displayLocale="en"
            name="usd"
            defaultValue={12345678.9}
          />

          <FormKit
            type="currency"
            currency="EUR"
            displayLocale="de"
            name="eur"
            defaultValue={12345678.9}
          />

          <FormKit
            type="currency"
            currency="INR"
            displayLocale="en-IN"
            name="inr"
            defaultValue={12345678.9}
          />

          <FormKit
            type="currency"
            currency="CNY"
            displayLocale="zh-CN"
            name="cny"
            defaultValue={12345678.9}
          />
          {/* %partial% */}
          <pre>{JSON.stringify(value, null, 2)}</pre>
        </>
      )}
    </FormKit>
  )
}

// .examples/currency/currency-simple-locale.vue
<script setup>
import { ref } from 'vue'
const value = ref(false)
</script>

<template>
  <!--
    FormKit forms auto-collect values of children inputs.
    Wrap the example in a form so we can display the form values.
  -->
  <FormKit type="form" #default="{ value }" :actions="false">
    <!-- %partial%::html:: -->
    <FormKit
      type="currency"
      currency="USD"
      displayLocale="en-US"
      name="usd"
      value="12345678.90"
    />

    <FormKit
      type="currency"
      currency="EUR"
      displayLocale="de-DE"
      name="eur"
      value="12345678.90"
    />

    <FormKit
      type="currency"
      currency="INR"
      displayLocale="en-IN"
      name="inr"
      value="12345678.90"
    />

    <FormKit
      type="currency"
      currency="CNY"
      displayLocale="zh-CN"
      name="cny"
      value="12345678.90"
    />
    <!-- %partial%::html:: -->
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>
